// import './js/module-1-1.js';
// import './js/variables.js';
// import './js/primitives.js';
// import './js/toString.js';
// import './js/toNumber.js';
// import './js/toBoolean.js';
// import './js/falsy-values.js';
//import './js/module-1-2.js';
// import './js/adddition-lesson-1.js';
// import './js/repeta-1-2.js';
// import './js/module-2-1.js';
// import './js/chat-bot-2.js';
// import './js/repeta-2-1.js';
// import './js/module-2-2.js';
// import './js/repeta-2-2.js';
// import "./js/morskoi-boi.js";
import "./js/repeta-3-1.js";
